### PR TITLE
Extended so that delete deltas can have an attribute too

### PR DESCRIPTION
**Pull request by rikh42**

### CODE REVIEW

**Comment by jhchen** [comment]
Please elaborate

**Comment by rikh42** [comment]
At the moment `delete` operations can not have attributes linked to them. This makes sense when attributes are only used for visual styling.

However, we have built a collaborative editor using Quill with an option to view your revision history. This requires that we know who made which changes in the document, including deletions. We do this using attributes on the content. eg `{insert: 'hello', attributes: { who: 1234}}`.

By extending Delta (well, removing the special treatment of `delete` operations in many cases, simplifying it), we can also track who was responsible for delete operations as well. There are other use cases for tracking attributes on deletions (eg why was this deleted).

I've added a PR as I felt this made Delta more general case, and less specific to being for styled content in Quill.

**Comment by rikh42** [comment]
If you compose any of the example diffs you gave, with the document, you would end up with the same empty document eg `{}`. However, as the attributes are present in the diff, it is possible to determine intent and meaning for the delete operations beyond the simple request to delete something.

The addition of the attributes in the delete operation allows us to write a new form of compose that outputs a 'visual diff' when given a document and diff. For example, the output of the `visualDiff` function might look like this...

Doc: `{insert: 'hello' attributes: { who: 'abc123' }}`
Diff: `{delete: 2, attributes: { who: 'abc123' }}, { delete: 3, attributes: { who: 'def456' }}`

Resulting Document used to display the diff: 
```{insert: 'he' attributes: { 'revision-history': 'deleted', who: 'abc123' }}, 
{insert: 'llo' attributes: { 'revision-history': 'deleted', who: 'def456' }}```

This might end up being displayed like so (with an appropriate extension to Quill that understands revision-history attributes)...

<img width="434" alt="diff" src="https://user-images.githubusercontent.com/715133/42151591-5fbfd30c-7dd5-11e8-9d3f-bfbd738195cd.png">

Whilst this doesn't specifically help with anything relating to operational transforms, it does not hinder it in any way either (in other words, all the existing ot functions work the same as they did before, giving the same output as they did before). The change here allows for a new extended use case that makes Deltas more useful in a collaborative environment (which is one of the main use cases for ot in the first place).

**Comment by rikh42** [comment]
Another way to think about this: 

Without this change it is impossible to know anything about delete operations (beyond the fact that something is to be deleted). Arbitrary data can be tracked for insert and retain operations though.

With the change, it is possible to know arbitrary data about any operation (insert, retain or delete) that can be interpreted by the implementation in any way it sees fit (we choose to use it to track the identity of the user that performed the delete, which is useful information in the context of a collaborative text editor)

**Comment by jhchen** [comment]
Deltas are not just data structures, they are instructions. `insert: 'text', attributes: { bold: true }` means inserted bolded text; `retain: 4, attributes: { bold: true }` means bold the next four characters; `delete: 4, attributes: { bold: true }` makes no sense. This proposal seems logically inconsistent with the purpose of Deltas. Implementing logically inconsistent functionality is guaranteed to result in unexpected and undesirable behavior.

**Comment by rikh42** [comment]
How would you feel about a metadata property for each operation instead? eg
`{ insert: 'hello', attributes: { bold: true}, meta: { who: 'abc123' }}`

**Comment by jhchen** [comment]
The proper solution for your use case is to make Deltas invertible https://github.com/ottypes/docs#optional-properties and one would do that by changing delete so it is not just an integer but also stores what was deleted. It is possible the proposal of adding `meta` could work but feels tacked on. If you want to think through and describe all cases of interaction and get the conceptual robustness to where invertibility is I will reconsider.

**Pull request closed without merging**
