### PR TITLE
Remove `package-lock.json`

### PR DESCRIPTION
**Pull request by alecgibson**
`package-lock.json` is [not published][1], so it shouldn't be committed
in packages, since running a build with a lockfile will not give a
true representation of how a consumer would be installing dependencies.

[1]: https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#package-lockjson-vs-npm-shrinkwrapjson

### CODE REVIEW

**Comment by jhchen** [comment]
I don't believe this is [best practice](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5). Please cite sources to the contrary.

**Comment by alecgibson** [comment]
This sums up what I consider best practice around this: https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi

In short:

- commit `package-lock.json` if your repo is a standalone app
- don't commit it if your repo is a package (ie intended to be a dependency of other apps)

**Comment by alecgibson** [comment]
Obviously this is your repo, so obviously do whatever you think is best; I just raised this in case the lockfile had been accidentally committed.

**Comment by jhchen** [comment]
You can see in the commit history it is not an accident. I agree with the top commenter on that blog post who is a maintainer of yarn that one should always commit package-lock.json for the reason he gives. This is also in addition to official NPM docs which that blog posts tries to spin as a source of confusion.

**Pull request closed without merging**
